name: Build AnimeDL

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install aqt
        run: |
          python -m pip install --upgrade pip
          python -m pip install aqtinstall

      - name: Install Qt 6.10.3
        run: |
          python -m aqt install-qt windows desktop 6.10.3 win64_mingw --outputdir Qt

      - name: Add Qt to PATH
        shell: pwsh
        run: |
          "$PWD/Qt/Tools/mingw1310_64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          "$PWD/Qt/6.10.3/mingw_64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      
      - name: List available tools
        run: |
          python -m aqt list-tool windows desktop
      
      - name: Clean build
        run: |
          Remove-Item build -Recurse -Force -ErrorAction Ignore
          
      - name: Install MinGW 13.1
        run: |
          python -m aqt install-tool windows desktop tools_mingw1310 --outputdir Qt

      - name: Verify MinGW
        shell: pwsh
        run: |
          Get-ChildItem Qt/Tools
          Get-ChildItem Qt/Tools/mingw1310_64/bin | Select-Object Name

      - name: Configure CMake
        shell: pwsh
        run: |
          cmake -S . -B build `
            -G "MinGW Makefiles" `
            -DCMAKE_PREFIX_PATH="$PWD/Qt/6.10.3/mingw_64" `
            -DCMAKE_C_COMPILER="$PWD/Qt/Tools/mingw1310_64/bin/gcc.exe" `
            -DCMAKE_CXX_COMPILER="$PWD/Qt/Tools/mingw1310_64/bin/g++.exe"

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Deploy Qt
        shell: pwsh
        run: |
          & "$PWD/Qt/6.10.3/mingw_64/bin/windeployqt.exe" `
            --release `
            --compiler-runtime `
            --no-translations `
            --no-system-d3d-compiler `
            --no-opengl-sw `
            build/animedl.exe

      - name: Cleanup distribution
        shell: pwsh
        run: |
          # CMake artifacts
          Remove-Item build/animedl_autogen -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item build/CMakeFiles -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item build/CMakeCache.txt -Force -ErrorAction SilentlyContinue
          Remove-Item build/cmake_install.cmake -Force -ErrorAction SilentlyContinue
          Remove-Item build/Makefile -Force -ErrorAction SilentlyContinue

          # Unused Qt components
          Remove-Item build/generic -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item build/networkinformation -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item build/tls -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item build/iconengines -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item build/imageformats -Recurse -Force -ErrorAction SilentlyContinue

          Remove-Item build/Qt6Network.dll -Force -ErrorAction SilentlyContinue
          Remove-Item build/Qt6Svg.dll -Force -ErrorAction SilentlyContinue

      - uses: actions/upload-artifact@v4
        with:
          name: animedl
          path: build/**

  build-linux:
      runs-on: ubuntu-22.04

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        # --------------------------------------------------------
        # System dependencies
        # --------------------------------------------------------

        - name: Install dependencies
          run: |
            sudo apt-get update

            sudo apt-get install -y \
              build-essential \
              cmake \
              ninja-build \
              wget \
              file \
              patchelf \
              libgl1-mesa-dev \
              libxkbcommon-dev \
              libxkbcommon-x11-0 \
              libxkbcommon-x11-dev \
              libxcb-cursor0 \
              libxcb-xinerama0 \
              libxcb1 \
              libxcb1-dev \
              libxcb-icccm4 \
              libxcb-image0 \
              libxcb-keysyms1 \
              libxcb-render-util0 \
              libxcb-shape0 \
              libxcb-shm0 \
              libxcb-util1 \
              libxcb-xkb1

        # --------------------------------------------------------
        # Qt
        # --------------------------------------------------------

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.13"

        - name: Install aqt
          run: |
            python -m pip install --upgrade pip
            python -m pip install aqtinstall

        - name: Install Qt 6.10.3
          run: |
            python -m aqt install-qt \
              linux \
              desktop \
              6.10.3 \
              linux_gcc_64 \
              --outputdir Qt

        - name: Add Qt to PATH
          run: |
            echo "$GITHUB_WORKSPACE/Qt/6.10.3/gcc_64/bin" >> "$GITHUB_PATH"

        - name: Verify Qt
          run: |
            qmake --version
            cmake --version
            gcc --version

        # --------------------------------------------------------
        # Build
        # --------------------------------------------------------

        - name: Configure CMake
          run: |
            cmake \
              -S . \
              -B build \
              -G Ninja \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/Qt/6.10.3/gcc_64"

        - name: Build
          run: |
            cmake --build build --config Release

        - name: Verify Linux binary
          run: |
            file build/animedl
            ldd build/animedl || true

        # --------------------------------------------------------
        # AppDir
        # --------------------------------------------------------

        - name: Create AppDir
          run: |
            rm -rf AppDir

            mkdir -p AppDir/usr/bin
            mkdir -p AppDir/usr/share/applications
            mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps

            cp build/animedl \
              AppDir/usr/bin/animedl

            cp icons/icon.png \
              AppDir/usr/share/icons/hicolor/256x256/apps/animedl.png

        # --------------------------------------------------------
        # Desktop file
        # --------------------------------------------------------

        - name: Create desktop file
          run: |
            cat > AppDir/usr/share/applications/animedl.desktop << 'EOF'
            [Desktop Entry]
            Type=Application
            Name=Anime Downloader
            Comment=AnimeDL
            Exec=animedl
            Icon=animedl
            Categories=AudioVideo;
            Terminal=false
            EOF

        # --------------------------------------------------------
        # Download linuxdeploy
        # --------------------------------------------------------

        - name: Download linuxdeploy
          run: |
            wget -q \
              https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage \
              -O linuxdeploy.AppImage

            chmod +x linuxdeploy.AppImage

        # --------------------------------------------------------
        # Download Qt plugin
        # --------------------------------------------------------

        - name: Download linuxdeploy Qt plugin
          run: |
            wget -q \
              https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage \
              -O linuxdeploy-plugin-qt.AppImage

            chmod +x linuxdeploy-plugin-qt.AppImage

        # --------------------------------------------------------
        # Deploy dependencies
        # --------------------------------------------------------

        - name: Deploy application
          env:
            QMAKE: ${{ github.workspace }}/Qt/6.10.3/gcc_64/bin/qmake
          run: |
            ./linuxdeploy.AppImage \
              --appdir AppDir \
              --plugin qt

        # --------------------------------------------------------
        # Build AppImage
        # --------------------------------------------------------

        - name: Build AppImage
          run: |
            ./linuxdeploy.AppImage \
              --appdir AppDir \
              --output appimage

        # --------------------------------------------------------
        # Rename
        # --------------------------------------------------------

        - name: Rename AppImage
          run: |
            APPIMAGE=$(find . -maxdepth 1 -type f -name '*.AppImage' -print -quit)

            if [ -z "$APPIMAGE" ]; then
              echo "ERROR: No AppImage was generated"
              exit 1
            fi

            mv "$APPIMAGE" AnimeDL-x86_64.AppImage

        # --------------------------------------------------------
        # Verify
        # --------------------------------------------------------

        - name: Verify AppImage
          run: |
            file AnimeDL-x86_64.AppImage
            ls -lh AnimeDL-x86_64.AppImage

        # --------------------------------------------------------
        # Upload
        # --------------------------------------------------------

        - name: Upload Linux artifact
          uses: actions/upload-artifact@v4
          with:
            name: animedl-linux
            path: AnimeDL-x86_64.AppImage